Make redis more like postgres plugin

diff --git a/plugins/redis/commands b/plugins/redis/commands
--- a/plugins/redis/commands
+++ b/plugins/redis/commands
@@ -31,50 +31,52 @@ function get_redis_port() {
 case "$1" in
 
 	redis:create)
-		REDIS_IMAGE=redis/$APP
+		DB_IMAGE=redis/$APP
+		DB_VERSION="$3"
+		if [ -z "$DB_VERSION" ]; then
+			DB_VERSION="latest"
+		fi
+
 		# Check if Redis container is installed
-		IMAGE=$(docker images | grep "dokkuinstaller/redis " |  awk '{print $3}')
+		IMAGE=$(docker images | grep "dokkuinstaller/redis" | grep "$DB_VERSION" |  awk '{print $3}')
 		if [[ -z $IMAGE ]]; then
-			echo "Redis image not found... Did you run 'dokku plugins-install' ?"
+        	echo "Redis image not found... Did you run 'dokku plugins-install' ?"
 			exit 1
 		fi
+
 		# Check if an existing DB volume exists
-		HOST_DIR="$DOKKU_ROOT/.redis/volume-$APP"
-		if [[ -d $HOST_DIR ]]; then
-			echo
-			echo "-----> Reusing redis/$APP database"
-		else
-			mkdir -p $HOST_DIR
+		if ! [[ -d "$DOKKU_ROOT/.redis/volume_$APP" ]]; then
+			# Create the DB directory
+			mkdir -p "$DOKKU_ROOT/.redis/volume_$APP"
+			chown dokku: "$DOKKU_ROOT/.redis/volume_$APP"
+			chmod 700 "$DOKKU_ROOT/.redis/volume_$APP"
 		fi
-		VOLUME="$HOST_DIR:/var/lib/redis"
-		# Stop existing container with the same persistent Redis
-		ID=$(docker ps | grep "$REDIS_IMAGE":latest |  awk '{print $1}')
-		if [[ ! -z "$ID" ]]; then
-			docker stop $ID > /dev/null
-		fi
+		VOLUME="$DOKKU_ROOT/.redis/volume_$APP:/var/lib/redis"
+
 		# Fork Redis image
-		ID=$(docker run -d dokkuinstaller/redis /bin/bash "exit 0")
+		ID=$(docker run -d "dokkuinstaller/redis:$DB_VERSION" echo '')
 		docker wait $ID > /dev/null
 		IMAGE=$(docker commit $ID)
-		docker tag $IMAGE $REDIS_IMAGE
+		docker tag $IMAGE $DB_IMAGE
+
 		# Launch container
-		ID=$(docker run -v $VOLUME -p 6379 -d $REDIS_IMAGE /bin/start_redis.sh)
+		ID=$(docker run -v $VOLUME -p 6379 -d $DB_IMAGE /bin/start_redis.sh)
 		sleep 4
 		echo
-		echo "-----> Redis container created: $REDIS_IMAGE"
+		echo "-----> Redis container created: $DB_IMAGE"
 		sleep 1
 		dokku redis:info $APP
 		;;
 
 	redis:delete)
-		REDIS_IMAGE=redis/$APP
+		DB_IMAGE=redis/$APP
 		# Stop the container
-		ID=$(docker ps -a | grep "$REDIS_IMAGE":latest |  awk '{print $1}')
+		ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
 		if [[ ! -z $ID ]]; then
 			docker stop $ID
 		fi
 		# Remove image
-		IMAGE=$(docker images | grep "$REDIS_IMAGE " |  awk '{print $1}')
+		IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
 		if [[ ! -z $IMAGE ]]; then
 			docker rmi $IMAGE
 		fi
@@ -84,12 +86,12 @@ case "$1" in
 			rm -rf $HOST_DIR
 		fi
 		echo
-		echo "-----> Redis container deleted: $REDIS_IMAGE"
+		echo "-----> Redis container deleted: $DB_IMAGE"
 		;;
 
 	redis:info)
-		REDIS_IMAGE=redis/$APP
-		ID=$(docker ps -a | grep "$REDIS_IMAGE":latest |  awk '{print $1}')
+		DB_IMAGE=redis/$APP
+		ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
 		IP="172.17.42.1"
 		PORT=$(docker port $ID 6379 | cut -d":" -f2)
 		echo
@@ -105,8 +107,8 @@ case "$1" in
 				echo "You must specify a container name"
 				exit 1
 			fi
-			REDIS_IMAGE="redis/$3"
-			ID=$(docker ps -a | grep "$REDIS_IMAGE":latest |  awk '{print $1}')
+			DB_IMAGE="redis/$3"
+			ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
 			if [[ -n "$ID" ]]; then
 				PORT=$(get_redis_port)
 
@@ -119,14 +121,14 @@ case "$1" in
 				ENV_TEMP="${ENV_TEMP}\nexport ${REDIS_URL}"
 				echo -e "$ENV_TEMP" | sed '/^$/d' | sort > $ENV_FILE
 				echo
-				echo "-----> $APP linked to $REDIS_IMAGE container"
+				echo "-----> $APP linked to $DB_IMAGE container"
 			fi
 		fi
 		;;
 
 	redis:logs)
-		REDIS_IMAGE=redis/$APP
-		ID=$(docker ps -a | grep "$REDIS_IMAGE" |  awk '{print $1}')
+		DB_IMAGE=redis/$APP
+		ID=$(docker ps -a | grep "$DB_IMAGE" |  awk '{print $1}')
 		docker logs $ID | tail -n 100
 		;;
 
