Revert bdf81de..1a7d54a
This rolls back to commit bdf81de5e823c58d4c58b8d84fd75fd15ceda422.

diff --git a/plugins/redis/commands b/plugins/redis/commands
--- a/plugins/redis/commands
+++ b/plugins/redis/commands
@@ -17,64 +17,45 @@ if [[ $1 == redis:* ]]; then
     fi
 fi
 
-# Create .redis diretory if not exists
-if [[ ! -d $DOKKU_ROOT/.redis ]]; then
-    mkdir -p $DOKKU_ROOT/.redis
-    chown -R dokku: $DOKKU_ROOT/.redis
-fi
-
 case "$1" in
 
   redis:create)
-	REDIS_IMAGE=redis/$APP
-	REDIS_VERSION="$3"
-	if [ -z "$REDIS_VERSION" ]; then
-		REDIS_VERSION="latest"
-	fi
-
-	# Check if DB container is installed
-	IMAGE=$(docker images | grep "dokkuinstaller/redis" | grep "$REDIS_VERSION" |  awk '{print $3}')
-	if [[ -z $IMAGE ]]; then
-	  	echo "Redis image not found... Did you run 'dokku plugins-install' ?"
-		exit 1
-	fi
-
-	# Check if an existing Redis volume exists
-	if [[ -f "$DOKKU_ROOT/.redis/volume_$APP" ]]; then
-		VOLUME="`cat $DOKKU_ROOT/.redis/volume_$APP`:/var/lib/redis"
-		echo
-		echo "-----> Reusing redis/$APP database"
-	else
-		VOLUME="/var/lib/redis"
-	fi
-
-	# Fork DB image
-	ID=$(docker run -d "dokkuinstaller/redis:$DB_VERSION" echo '')
-	docker wait $ID > /dev/null
-	IMAGE=$(docker commit $ID)
-	docker tag $IMAGE $DB_IMAGE
-
-	# Launch container
-	ID=$(docker run -v $VOLUME -p 6379 -d $REDIS_IMAGE /bin/start_redis.sh)
-	sleep 4
-
-	# Rename persistent volume
-	if [[ ! -f "$DOKKU_ROOT/.redis/volume_$APP" ]]; then
-		VOLUME_PATH=$(docker inspect $ID | grep /var/lib/docker/vfs/dir/ | awk '{print $2}' | sed -e's/"//g')
-		if [[ -z $VOLUME_PATH ]]; then
-			echo "Your docker version is too old, please update it"
-			exit 1
-		fi
-		echo $VOLUME_PATH > "$DOKKU_ROOT/.redis/volume_$APP"
-	fi
-
-	# Link to a potential existing app
-	dokku redis:link $APP $APP
-	echo
-	echo "-----> Redis container created: $DB_IMAGE"
-	sleep 1
-	dokku redis:info $APP
-	;;
+    REDIS_IMAGE=redis/$APP
+    # Check if Redis container is installed
+    IMAGE=$(docker images | grep "luxifer/redis " |  awk '{print $3}')
+    if [[ -z $IMAGE ]]; then
+        echo "Redis image not found... Did you run 'dokku plugins-install' ?"
+        exit 1
+    fi
+    # Check if an existing DB volume exists
+    HOST_DIR="$DOKKU_ROOT/.redis/volume-$APP"
+    if [[ -d $HOST_DIR ]]; then
+        echo
+        echo "-----> Reusing redis/$APP database"
+    else
+        mkdir -p $HOST_DIR
+    fi
+    VOLUME="$HOST_DIR:/var/lib/redis"
+    # Stop existing container with the same persistent Redis
+    ID=$(docker ps | grep "$REDIS_IMAGE":latest |  awk '{print $1}')
+    if [[ ! -z "$ID" ]]; then
+        docker stop $ID > /dev/null
+    fi
+    # Fork Redis image
+    ID=$(docker run -d luxifer/redis /bin/bash "exit 0")
+    docker wait $ID > /dev/null
+    IMAGE=$(docker commit $ID)
+    docker tag $IMAGE $REDIS_IMAGE
+    # Launch container
+    ID=$(docker run -v $VOLUME -p 6379 -d $REDIS_IMAGE /bin/start_redis.sh)
+    sleep 4
+    # Link to a potential existing app
+    dokku redis:link $APP $APP
+    echo
+    echo "-----> Redis container created: $REDIS_IMAGE"
+    sleep 1
+    dokku redis:info $APP
+    ;;
 
   redis:delete)
     REDIS_IMAGE=redis/$APP
@@ -89,7 +70,7 @@ case "$1" in
         docker rmi $IMAGE
     fi
     # Remove persistent volume
-    HOST_DIR="$DOKKU_ROOT/.redis/volume_$APP"
+    HOST_DIR="$DOKKU_ROOT/.redis/volume-$APP"
     if [[ -d $HOST_DIR ]]; then
         rm -rf $HOST_DIR
     fi
@@ -119,8 +100,15 @@ case "$1" in
         ID=$(docker ps -a | grep "$REDIS_IMAGE":latest |  awk '{print $1}')
         if [[ -n "$ID" ]]; then
             PORT=$(docker port "$ID" 6379 | sed 's/0.0.0.0://')
-			# Link database using dokku command
-			dokku config:set $APP "REDIS_URL=redis://172.17.42.1:$PORT"
+            # Write REDIS_IP to app's ENV file
+            REDIS_URL="REDIS_URL=redis://172.17.42.1:$PORT"
+            ENV_FILE="$DOKKU_ROOT/$APP/ENV"
+            if [[ ! -f $ENV_FILE ]]; then
+                touch $ENV_FILE
+            fi
+            ENV_TEMP=$(cat "${ENV_FILE}" | sed "/^export REDIS_URL=/ d")
+            ENV_TEMP="${ENV_TEMP}\nexport ${REDIS_URL}"
+            echo -e "$ENV_TEMP" | sed '/^$/d' | sort > $ENV_FILE
             echo
             echo "-----> $APP linked to $REDIS_IMAGE container"
         fi
