Updated deployment check

diff --git a/plugins/checks/check-deploy b/plugins/checks/check-deploy
--- a/plugins/checks/check-deploy
+++ b/plugins/checks/check-deploy
@@ -8,6 +8,7 @@ APP="$2"; PORT="$3"
 echo "DOKKU_CHECKS_WAIT is $DOKKU_CHECKS_WAIT"
 FILENAME="$DOKKU_ROOT/$APP/CHECKS"
 WAIT="${DOKKU_CHECKS_WAIT:-5}"
+MAX_ATTEMPTS=5
 
 echo "Waiting $WAIT seconds ..."
 sleep $WAIT
@@ -21,26 +22,26 @@ URL="http://localhost:$PORT/"
 
 attempts=0
 
-until [ $attempts -ge 5 ]
+until [ $attempts -ge $MAX_ATTEMPTS ]
 do
 	echo "checking with: curl $CURL_OPTIONS $URL"
 	if OUTPUT=$(curl -I $CURL_OPTIONS $URL 2>&1) ; then
 		if [[ "$OUTPUT" =~ "HTTP/1.1 200 OK" ]] ; then
+			SUCCESS=true
 			echo "HTTP/1.1 200 OK" && break
-		else
-			echo "Expected HTTP/1.1 200 OK"
-			echo "Response:"
-			echo $OUTPUT
 		fi
-	else
-		echo "FAILED ATTEMPT"
-		echo "Response:"
-		echo $OUTPUT
 	fi
 	attempts=$[$attempts+1]
 	echo "FAILED ATTEMPT #$attempts"
+	echo "Response:"
+	echo $OUTPUT
 	echo "Waiting $WAIT seconds ..."
 	sleep $WAIT
 done
 
-echo -e "\033[32m\033[1mAll checks successful!\033[0m"
+if [[ -z $SUCCESS ]] ; then
+	echo -e "\033[32m\033[1mAll checks successful!\033[0m"
+else
+	echo "FAILED TO LOAD APP"
+	exit 2
+fi
