Update commands to use 4-space tabs

diff --git a/plugins/postgres/commands b/plugins/postgres/commands
--- a/plugins/postgres/commands
+++ b/plugins/postgres/commands
@@ -59,173 +59,173 @@ function connect_to_db() {
 
 case "$1" in
 
-  postgres:console)
-    check_postgres_container
-    check_postgres_tool psql
-    connect_to_db
-    ;;
+	postgres:console)
+		check_postgres_container
+		check_postgres_tool psql
+		connect_to_db
+		;;
 
-  postgres:create)
-    DB_IMAGE=postgres/$APP
-    # Check if DB container is installed
-    IMAGE=$(docker images | grep "dokkuinstaller/postgres " |  awk '{print $3}')
-    if [[ -z $IMAGE ]]; then
-        echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
-        exit 1
-    fi
-    # Check if an existing DB volume exists
-    if [[ -f "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
-        VOLUME="`cat $DOKKU_ROOT/.postgres/volume_$APP`:/opt/postgres"
-        echo
-        echo "-----> Reusing postgres/$APP database"
-    else
-        VOLUME="/opt/postgres"
-        # Generate a random password for DB user
-        DB_PASSWORD=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
-        echo $DB_PASSWORD > "$DOKKU_ROOT/.postgres/pwd_$APP"
-        chown dokku: "$DOKKU_ROOT/.postgres/pwd_$APP"
-        chmod 700 "$DOKKU_ROOT/.postgres/pwd_$APP"
-    fi
-    # Fork DB image
-    ID=$(docker run -d dokkuinstaller/postgres echo '')
-    docker wait $ID > /dev/null
-    IMAGE=$(docker commit $ID)
-    docker tag $IMAGE $DB_IMAGE
-    # Launch container
-    ID=$(docker run -v $VOLUME -p 5432 -d $DB_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD)
-    sleep 4
-    # Rename persistent volume
-    if [[ ! -f "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
-        VOLUME_PATH=$(docker inspect $ID | grep /var/lib/docker/vfs/dir/ | awk '{print $2}' | sed -e's/"//g')
-        if [[ -z $VOLUME_PATH ]]; then
-            echo "Your docker version is too old, please update it"
-            exit 1
-        fi
-        echo $VOLUME_PATH > "$DOKKU_ROOT/.postgres/volume_$APP"
-    fi
-    # Link to a potential existing app
-    dokku postgres:link $APP $APP
-    echo
-    echo "-----> PostgreSQL container created: $DB_IMAGE"
-    sleep 1
-    dokku postgres:info $APP
-    ;;
+	postgres:create)
+		DB_IMAGE=postgres/$APP
+		# Check if DB container is installed
+		IMAGE=$(docker images | grep "dokkuinstaller/postgres " |  awk '{print $3}')
+		if [[ -z $IMAGE ]]; then
+        	echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
+			exit 1
+		fi
+		# Check if an existing DB volume exists
+		if [[ -f "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
+			VOLUME="`cat $DOKKU_ROOT/.postgres/volume_$APP`:/opt/postgres"
+			echo
+			echo "-----> Reusing postgres/$APP database"
+		else
+			VOLUME="/opt/postgres"
+			# Generate a random password for DB user
+			DB_PASSWORD=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
+			echo $DB_PASSWORD > "$DOKKU_ROOT/.postgres/pwd_$APP"
+			chown dokku: "$DOKKU_ROOT/.postgres/pwd_$APP"
+			chmod 700 "$DOKKU_ROOT/.postgres/pwd_$APP"
+		fi
+		# Fork DB image
+		ID=$(docker run -d dokkuinstaller/postgres echo '')
+		docker wait $ID > /dev/null
+		IMAGE=$(docker commit $ID)
+		docker tag $IMAGE $DB_IMAGE
+		# Launch container
+		ID=$(docker run -v $VOLUME -p 5432 -d $DB_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD)
+		sleep 4
+		# Rename persistent volume
+		if [[ ! -f "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
+			VOLUME_PATH=$(docker inspect $ID | grep /var/lib/docker/vfs/dir/ | awk '{print $2}' | sed -e's/"//g')
+			if [[ -z $VOLUME_PATH ]]; then
+				echo "Your docker version is too old, please update it"
+				exit 1
+			fi
+			echo $VOLUME_PATH > "$DOKKU_ROOT/.postgres/volume_$APP"
+		fi
+		# Link to a potential existing app
+		dokku postgres:link $APP $APP
+		echo
+		echo "-----> PostgreSQL container created: $DB_IMAGE"
+		sleep 1
+		dokku postgres:info $APP
+		;;
 
-  postgres:delete)
-    DB_IMAGE=postgres/$APP
-    ID=$(get_postgres_id)
-    # Stop and remove the container
-    if [[ ! -z $ID ]]; then
-        docker kill $ID > /dev/null
-        sleep 1
-        docker rm -v $ID > /dev/null
-        sleep 1
-    fi
-    # Remove image
-    IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
-    if [[ ! -z $IMAGE ]]; then
-        docker rmi $IMAGE > /dev/null
-    fi
-    # Remove container root password
-    if [[ -f "$DOKKU_ROOT/.postgres/pwd_$APP" ]]; then
-        rm -f "$DOKKU_ROOT/.postgres/pwd_$APP"
-    fi
-    # Remove persistent volume
-    if [[ -f "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
-        rm -f "$DOKKU_ROOT/.postgres/volume_$APP"
-    fi
+	postgres:delete)
+		DB_IMAGE=postgres/$APP
+		ID=$(get_postgres_id)
+		# Stop and remove the container
+		if [[ ! -z $ID ]]; then
+			docker kill $ID > /dev/null
+			sleep 1
+			docker rm -v $ID > /dev/null
+			sleep 1
+		fi
+		# Remove image
+		IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
+		if [[ ! -z $IMAGE ]]; then
+			docker rmi $IMAGE > /dev/null
+		fi
+		# Remove container root password
+		if [[ -f "$DOKKU_ROOT/.postgres/pwd_$APP" ]]; then
+			rm -f "$DOKKU_ROOT/.postgres/pwd_$APP"
+		fi
+		# Remove persistent volume
+		if [[ -f "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
+			rm -f "$DOKKU_ROOT/.postgres/volume_$APP"
+		fi
 
-    echo
-    echo "-----> PostgreSQL container deleted: $DB_IMAGE"
-    ;;
+		echo
+		echo "-----> PostgreSQL container deleted: $DB_IMAGE"
+		;;
 
-  postgres:dump)
-    check_postgres_container
-    check_postgres_tool pg_dump
-    export PGPASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
-    PORT=$(get_postgres_port)
+	postgres:dump)
+		check_postgres_container
+		check_postgres_tool pg_dump
+		export PGPASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
+		PORT=$(get_postgres_port)
 
-    pg_dump -h 172.17.42.1 -p $PORT -U root -c -O db
+		pg_dump -h 172.17.42.1 -p $PORT -U root -c -O db
 
-    # echo to stderr, as stdout will probably be redirected to a file
-    echo 1>&2
-    echo "-----> $APP database dumped" 1>&2
-    ;;
+		# echo to stderr, as stdout will probably be redirected to a file
+		echo 1>&2
+		echo "-----> $APP database dumped" 1>&2
+		;;
 
-  postgres:info)
-    check_postgres_container
-    DB_PASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
-    PORT=$(get_postgres_port)
+	postgres:info)
+		check_postgres_container
+		DB_PASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
+		PORT=$(get_postgres_port)
 
-    echo
-    echo "       Host: 172.17.42.1"
-    echo "       Port: $PORT"
-    echo "       User: 'root'"
-    echo "       Password: '$DB_PASSWORD'"
-    echo "       Database: 'db'"
-    echo
-    echo "       Url: 'postgres://root:$DB_PASSWORD@172.17.42.1:$PORT/db'"
-    echo
-    ;;
+		echo
+		echo "       Host: 172.17.42.1"
+		echo "       Port: $PORT"
+		echo "       User: 'root'"
+		echo "       Password: '$DB_PASSWORD'"
+		echo "       Database: 'db'"
+		echo
+		echo "       Url: 'postgres://root:$DB_PASSWORD@172.17.42.1:$PORT/db'"
+		echo
+		;;
 
-  postgres:link)
-    if $APP_EXISTS; then
-        # Check argument
-        if [[ -z $3 ]]; then
-            echo "You must specify a database name"
-            exit 1
-        fi
-        DB_IMAGE="postgres/$3"
-        if [[ ! -f "$DOKKU_ROOT/.postgres/pwd_$3" ]]; then
-            echo "Database is not initialized correctly. Did you run 'dokku plugins-install'?"
-            exit 1
-        fi
-        DB_PASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$3")
-        PORT=$(get_postgres_port)
-        # Link database using dokku command
-        dokku config:set $APP "DATABASE_URL=postgres://root:$DB_PASSWORD@172.17.42.1:$PORT/db"
-        echo
-        echo "-----> $APP linked to $DB_IMAGE database"
-    fi
-    ;;
+	postgres:link)
+		if $APP_EXISTS; then
+			# Check argument
+			if [[ -z $3 ]]; then
+				echo "You must specify a database name"
+				exit 1
+			fi
+			DB_IMAGE="postgres/$3"
+			if [[ ! -f "$DOKKU_ROOT/.postgres/pwd_$3" ]]; then
+				echo "Database is not initialized correctly. Did you run 'dokku plugins-install'?"
+				exit 1
+			fi
+			DB_PASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$3")
+			PORT=$(get_postgres_port)
+			# Link database using dokku command
+			dokku config:set $APP "DATABASE_URL=postgres://root:$DB_PASSWORD@172.17.42.1:$PORT/db"
+			echo
+			echo "-----> $APP linked to $DB_IMAGE database"
+		fi
+		;;
 
-  postgres:logs)
-    ID=$(get_postgres_id)
-    docker logs $ID | tail -n 100
-    ;;
+	postgres:logs)
+		ID=$(get_postgres_id)
+		docker logs $ID | tail -n 100
+		;;
 
-  postgres:list)
-    CONTAINERS=$(ls $DOKKU_ROOT/.postgres/volume* 2> /dev/null | sed -e 's/_/ /' | awk '{print $2}')
-    if [[ -z $CONTAINERS ]]; then
-        echo "There are no PostgreSQL containers created."
-    else
-        echo "PostgreSQL containers:"
-        for CONTAINER in $CONTAINERS; do
-            echo "  - $CONTAINER"
-        done
-    fi
-    ;;
+	postgres:list)
+		CONTAINERS=$(ls $DOKKU_ROOT/.postgres/volume* 2> /dev/null | sed -e 's/_/ /' | awk '{print $2}')
+		if [[ -z $CONTAINERS ]]; then
+			echo "There are no PostgreSQL containers created."
+		else
+			echo "PostgreSQL containers:"
+			for CONTAINER in $CONTAINERS; do
+				echo "  - $CONTAINER"
+			done
+		fi
+		;;
 
-  postgres:restore)
-    check_postgres_container
-    check_postgres_tool psql
-    connect_to_db
+	postgres:restore)
+		check_postgres_container
+		check_postgres_tool psql
+		connect_to_db
 
-    echo
-    echo "-----> $APP database restored"
-    ;;
+		echo
+		echo "-----> $APP database restored"
+		;;
 
 	help)
-    cat && cat<<EOF
-    postgres:console <db>															Open a PostgreSQL console
-    postgres:create <db>															Create a PostgreSQL container
-    postgres:delete <db>															Delete specified PostgreSQL container
-    postgres:dump <db> > dump_file.sql								Dump database data
-    postgres:info <db>																Display database informations
-    postgres:link <app> <db>													Link an app to a PostgreSQL database
-    postgres:list																			Display list of PostgreSQL containers
-    postgres:logs <db>																Display last logs from PostgreSQL container
-    postgres:restore <db> < dump_file.sql							Restore database data from a previous dump
+	cat && cat<<EOF
+	postgres:console <db>							Open a PostgreSQL console
+	postgres:create <db>							Create a PostgreSQL container
+	postgres:delete <db>							Delete specified PostgreSQL container
+	postgres:dump <db> > dump_file.sql				Dump database data
+	postgres:info <db>								Display database informations
+	postgres:link <app> <db>						Link an app to a PostgreSQL database
+	postgres:list									Display list of PostgreSQL containers
+	postgres:logs <db>								Display last logs from PostgreSQL container
+	postgres:restore <db> < dump_file.sql			Restore database data from a previous dump
 EOF
     ;;
 
