Trying out new postgres/redis plugins

diff --git a/plugins/postgres/commands b/plugins/postgres/commands
--- a/plugins/postgres/commands
+++ b/plugins/postgres/commands
@@ -3,7 +3,7 @@ set -e;
 
 # Check if name is specified
 if [[ $1 == postgres:* ]]; then
-    if [ -z $2 ] && [ $1 != postgres:list ]; then
+    if [[ -z $2 ]]; then
         echo "You must specify an app name"
         exit 1
     else
@@ -15,213 +15,113 @@ if [[ $1 == postgres:* ]]; then
             APP_EXISTS=false
         fi
     fi
-fi
-
-# Create .postgres diretory if not exists
-if [[ ! -d $DOKKU_ROOT/.postgres ]]; then
-    mkdir -p $DOKKU_ROOT/.postgres
-    chown -R dokku: $DOKKU_ROOT/.postgres
-fi
-
-function check_postgres_container() {
-    if [[ ! -f "$DOKKU_ROOT/.postgres/pwd_$APP" ]]; then
-        echo "Unknown (or too old) PostgreSQL container"
+    if [[ ! -d "$PLUGIN_PATH/link" ]]; then
+        echo "Link plugin not found... Did you install it from https://github.com/rlaneve/dokku-link?"
         exit 1
     fi
-}
 
-function check_postgres_tool() {
-    local tool_name="$1"
-    if [[ $(whereis $tool_name | awk '{ print NF }') -eq 1 ]]; then
-        echo "'${tool_name}' not found. Is the package 'postgres-client' installed?" 1>&2
-        exit 1
-    fi
-}
-
-function get_postgres_id() {
-    ID=$(docker ps -a | grep postgres/"$APP":latest | awk {'print $1'})
-    echo $ID
-}
-
-function get_postgres_port() {
-    ID=$(get_postgres_id)
-    PORT=$(docker port "$ID" 5432 | sed 's/0.0.0.0://')
-    echo $PORT
-}
-
-function connect_to_db() {
-    export PGPASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
-    PORT=$(get_postgres_port)
-
-    psql -h 172.17.42.1 -p $PORT -U root db
-}
+    PLUGIN_NAME="postgres"
+    CONTAINER_NAME="${PLUGIN_NAME}_$APP"
+    HOST_DIR="$DOKKU_ROOT/$APP/$PLUGIN_NAME"
+    ENVVAR_NAME="DATABASE_URL"
+fi
 
 case "$1" in
+  postgres:create)
+    # Check if Postgres container is installed
+    IMAGE=$(docker images | grep "jezdez/postgres" | awk '{print $3}')
+    if [[ -z $IMAGE ]]; then
+        echo "Postgres image not found... Did you run 'dokku plugins-install' ?"
+        exit 1
+    fi
 
-	postgres:console)
-		check_postgres_container
-		check_postgres_tool psql
-		connect_to_db
-		;;
+    # Stop existing container with the same persistent Postgres
+    ID=$(docker ps | grep "$CONTAINER_NAME" | awk '{print $1}')
+    if [[ ! -z "$ID" ]]; then
+        docker stop $ID > /dev/null
+    fi
 
-	postgres:create)
-		DB_IMAGE=postgres/$APP
-		DB_VERSION="$3"
-		if [ -z "$DB_VERSION" ]; then
-			DB_VERSION="latest"
-		fi
+    # Check if an existing DB volume exists
+    if [[ -d $HOST_DIR ]]; then
+        echo "-----> Reusing $CONTAINER_NAME data"
+    else
+        mkdir -p $HOST_DIR
+        chown -R dokku:dokku $HOST_DIR
+    fi
+    VOLUME="$HOST_DIR:/var/lib/postgresql"
+    PASS=$(openssl rand -base64 32|base64)
+    # Launch container
+    docker run -v $VOLUME -name=$CONTAINER_NAME -d \
+        -e POSTGRESQL_USER=${APP//[^a-zA-z0-9_]/''} -e POSTGRESQL_PASS=$PASS \
+        -e POSTGRESQL_DB=${APP//[^a-zA-z0-9_]/''} \
+        jezdez/postgres
 
-		# Check if DB container is installed
-		IMAGE=$(docker images | grep "dokkuinstaller/postgres" | grep "$DB_VERSION" |  awk '{print $3}')
-		if [[ -z $IMAGE ]]; then
-        	echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
-			exit 1
-		fi
+    # Link to a potential existing app
+    dokku postgres:link $APP $APP
+    echo "-----> Postgres container created: $CONTAINER_NAME"
+    sleep 1
+    dokku postgres:info $APP
+    ;;
 
-		# Check if an existing DB volume exists
-		if ! [[ -d "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
-			# Create the DB directory
-			mkdir -p "$DOKKU_ROOT/.postgres/volume_$APP"
+  postgres:delete)
+    # Stop the container
+    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
+    if [[ ! -z $ID ]]; then
+        docker stop $ID > /dev/null
+        docker rm $ID  > /dev/null
+    fi
+    # Remove persistent volume
+    if [[ -d $HOST_DIR ]]; then
+        rm -rf $HOST_DIR
+    fi
 
-			# Generate a random password for DB user
-			DB_PASSWORD=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
-			echo $DB_PASSWORD > "$DOKKU_ROOT/.postgres/pwd_$APP"
-			chown dokku: "$DOKKU_ROOT/.postgres/pwd_$APP"
-			chmod 700 "$DOKKU_ROOT/.postgres/pwd_$APP"
-		fi
-		VOLUME="$DOKKU_ROOT/.postgres/volume_$APP:/opt/postgresql"
+    # unlink this container as "postgres"
+    dokku link:delete "$APP" "$CONTAINER_NAME" "$PLUGIN_NAME"
+    dokku config:unset "$APP" $ENVVAR_NAME
+    echo "-----> Postgres container deleted: $CONTAINER_NAME"
+    ;;
 
-		# Fork DB image
-		ID=$(docker run -d "dokkuinstaller/postgres:$DB_VERSION" echo '')
-		docker wait $ID > /dev/null
-		IMAGE=$(docker commit $ID)
-		docker tag $IMAGE $DB_IMAGE
+  postgres:info)
+    ID=$(docker ps -a | grep "$CONTAINER_NAME" | awk '{print $1}')
+    IP=$(docker inspect $ID | grep IPAddress | cut -d '"' -f 4)
+    echo
+    echo "       Host: ${IP}"
+    echo "       Private port: 5432"
+    echo
+    ;;
 
-		# Launch container
-		ID=$(docker run -v $VOLUME -p 5432 -d $DB_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD)
-		sleep 4
+  postgres:link)
+    if $APP_EXISTS; then
+        # Check argument
+        if [[ -z $3 ]]; then
+            echo "You must specify a container name"
+            exit 1
+        fi
+        CONTAINER_NAME="postgres_$3"
 
-		echo
-		echo "-----> PostgreSQL container created: $DB_IMAGE"
-		sleep 1
-		dokku postgres:info $APP
-		;;
+        # link this container as "postgres"
+        dokku link:create "$APP" "$CONTAINER_NAME" "$PLUGIN_NAME"
 
-	postgres:delete)
-		DB_IMAGE=postgres/$APP
-		ID=$(get_postgres_id)
-		# Stop and remove the container
-		if [[ ! -z $ID ]]; then
-			docker kill $ID > /dev/null
-			sleep 1
-			docker rm -v $ID > /dev/null
-			sleep 1
-		fi
-		# Remove image
-		IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
-		if [[ ! -z $IMAGE ]]; then
-			docker rmi $IMAGE > /dev/null
-		fi
-		# Remove container root password
-		if [[ -f "$DOKKU_ROOT/.postgres/pwd_$APP" ]]; then
-			rm -f "$DOKKU_ROOT/.postgres/pwd_$APP"
-		fi
-		# Remove persistent volume
-		if [[ -f "$DOKKU_ROOT/.postgres/volume_$APP" ]]; then
-			rm -f "$DOKKU_ROOT/.postgres/volume_$APP"
-		fi
+        # figure out IP to set env var
+        ID=$(docker ps -a | grep "$CONTAINER_NAME" | awk '{print $1}')
+        IP=$(docker inspect $ID | grep IPAddress | cut -d '"' -f 4)
+        dokku config:set "$APP" $ENVVAR_NAME="postgres://${IP}:5432"
+        echo "-----> $APP linked to $CONTAINER_NAME container"
+    fi
+    ;;
 
-		echo
-		echo "-----> PostgreSQL container deleted: $DB_IMAGE"
-		;;
+  postgres:logs)
+    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
+    docker logs $ID | tail -n 100
+    ;;
 
-	postgres:dump)
-		check_postgres_container
-		check_postgres_tool pg_dump
-		export PGPASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
-		PORT=$(get_postgres_port)
-
-		pg_dump -h 172.17.42.1 -p $PORT -U root -c -O db
-
-		# echo to stderr, as stdout will probably be redirected to a file
-		echo 1>&2
-		echo "-----> $APP database dumped" 1>&2
-		;;
-
-	postgres:info)
-		check_postgres_container
-		DB_PASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$APP")
-		PORT=$(get_postgres_port)
-
-		echo
-		echo "       Host: 172.17.42.1"
-		echo "       Port: $PORT"
-		echo "       User: 'root'"
-		echo "       Password: '$DB_PASSWORD'"
-		echo "       Database: 'db'"
-		echo
-		echo "       Url: 'postgres://root:$DB_PASSWORD@172.17.42.1:$PORT/db'"
-		echo
-		;;
-
-	postgres:link)
-		if $APP_EXISTS; then
-			# Check argument
-			if [[ -z $3 ]]; then
-				echo "You must specify a database name"
-				exit 1
-			fi
-			DB_IMAGE="postgres/$3"
-			if [[ ! -f "$DOKKU_ROOT/.postgres/pwd_$3" ]]; then
-				echo "Database is not initialized correctly. Did you run 'dokku plugins-install'?"
-				exit 1
-			fi
-			DB_PASSWORD=$(cat "$DOKKU_ROOT/.postgres/pwd_$3")
-			PORT=$(get_postgres_port)
-			# Link database using dokku command
-			dokku config:set $APP "DATABASE_URL=postgres://root:$DB_PASSWORD@172.17.42.1:$PORT/db"
-			echo
-			echo "-----> $APP linked to $DB_IMAGE database"
-		fi
-		;;
-
-	postgres:logs)
-		ID=$(get_postgres_id)
-		docker logs $ID | tail -n 100
-		;;
-
-	postgres:list)
-		CONTAINERS=$(ls $DOKKU_ROOT/.postgres/volume* 2> /dev/null | sed -e 's/_/ /' | awk '{print $2}')
-		if [[ -z $CONTAINERS ]]; then
-			echo "There are no PostgreSQL containers created."
-		else
-			echo "PostgreSQL containers:"
-			for CONTAINER in $CONTAINERS; do
-				echo "  - $CONTAINER"
-			done
-		fi
-		;;
-
-	postgres:restore)
-		check_postgres_container
-		check_postgres_tool psql
-		connect_to_db
-
-		echo
-		echo "-----> $APP database restored"
-		;;
-
-    help)
+  help)
     cat && cat<<EOF
-    postgres:console <db>				Open a PostgreSQL console
-    postgres:create <db> [VERSION]			Create a PostgreSQL container
-    postgres:delete <db>				Delete specified PostgreSQL container
-    postgres:dump <db> > dump_file.sql			Dump database data
-    postgres:info <db>					Display database informations
-    postgres:link <app> <db>				Link an app to a PostgreSQL database
-    postgres:list					Display list of PostgreSQL containers
-    postgres:logs <db>					Display last logs from PostgreSQL container
-    postgres:restore <db> < dump_file.sql		Restore database data from a previous dump
+    postgres:create <app>				Create a Postgres container
+    postgres:delete <app>				Delete specified Postgres container
+    postgres:info <app>					Display container informations
+    postgres:link <app> <container>			Link an app to a Postgres container
+    postgres:logs <app>					Display last logs from Postgres container
 EOF
     ;;
 
